# Generated by Django 4.2.2 on 2023-06-12 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('persons', models.IntegerField(null=True)),
                ('difficulty', models.IntegerField(null=True)),
                ('category', models.CharField(choices=[('APPETIZER', 'Antipasto'), ('FIRST', 'Primo'), ('SECOND', 'Secondo'), ('SIDE', 'Contorno'), ('DESSERT', 'Dolce')], max_length=10, null=True)),
                ('preparation_time', models.TimeField(null=True)),
                ('ingredients', models.TextField(max_length=500, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipesharing.recipe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
    ]
